### ISSUE TITLE
Fails on unknown / not existing images

### ISSUE THREAD

**Issue by Jan-M** [zalando-stups/pierone-cli#22]
```
➜  zmon-checks git:(master) ✗ pierone tags stups zmon-agent
Traceback (most recent call last):
  File "/usr/local/bin/pierone", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/pierone/cli.py", line 250, in main
    cli()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pierone/cli.py", line 155, in tags
    r = get_tags(config.get('url'), team, art, token['access_token'])
  File "/usr/local/lib/python3.4/dist-packages/pierone/cli.py", line 124, in get_tags
    return r.json()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by hjacobs** [comment]
True, I already experienced this issue :disappointed:

**Comment by hjacobs** [comment]
Should be fixed in https://github.com/zalando-stups/pierone-cli/releases/tag/1.0.16
