### ISSUE TITLE
Cannot get image tags

### ISSUE THREAD

**Issue by PetrGlad** [zalando-stups/pierone-cli#53]
I am getting these exceptions while working with pierone. Also "senza update" complaints that respective image is not found but it is in the repository. It's weird that the error disappears occasionally (at one moment "senza update" was successfull and subsequent pirone commands were OK also).
```
$ uname -a
Linux auser 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$  senza --version
Senza 2.0.165
$ pierone --version
Pier One CLI 1.0.36
$ pierone login
Getting OAuth2 token "pierone".. OK
Storing Docker client configuration in /home/auser/.docker/config.json.. OK
$ pierone teams | grep acid
acid  
$ pierone tags acid
Traceback (most recent call last):
  File "/usr/local/bin/pierone", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pierone/cli.py", line 456, in main
    cli()
  File "/home/auser/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/auser/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/auser/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/auser/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/auser/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/auser/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pierone/cli.py", line 242, in tags
    tags = get_image_tags(image, token)
  File "/usr/local/lib/python3.5/dist-packages/pierone/api.py", line 130, in get_image_tags
    for entry in response.json()]
  File "/usr/local/lib/python3.5/dist-packages/pierone/api.py", line 130, in <listcomp>
    for entry in response.json()]
  File "/usr/local/lib/python3.5/dist-packages/pierone/api.py", line 152, in parse_pierone_artifact_dict
    'tag': original_payload_from_api['name'],
TypeError: string indices must be integers
```

**Comment by PetrGlad** [comment]
See also https://github.com/zalando-stups/pierone-cli/pull/54 that make errors more transparent.
